### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by luii**
I dont usually write the dependencies like this, but i need to for testing with sinon

### CODE REVIEW

**Comment by piranna** [comment]
Why can't they be used as before? What problem do you have?

**Comment by luii** [comment]
As stated in `nodeos-mount-utils` i get a error from sinon that it cant find the dependencies.
I dont know either why sinon does this but its better for testing

**Comment by piranna** [comment]
Yeah, I remember that, it's only that aparently both are equal, so I don't know why it would fail. Maybe a bug in the way sinon does the injection?

**Comment by luii** [comment]
Could be, but i dont know for sure

**Comment by luii** [comment]
@piranna as long its not breaking the api it should be ok or not? Its more a style question because so or so it will require the entire module

**Comment by piranna** [comment]
Yeah, it was more of a -0, I'll merge it.

**Comment by luii** [comment]
But not yet :D

**Comment by piranna** [comment]
L0l :-P

**Comment by luii** [comment]
Well i create a new PR for the other functions

**Comment by piranna** [comment]
Yeah, and I'll wait until you tell me it's ready ;-)

**Pull request merged**
